<?php
define('APP_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR);
define('CONTROLLER_PATH', APP_PATH . DIRECTORY_SEPARATOR . 'Controllers' . DIRECTORY_SEPARATOR);
define('MODEL_PATH', APP_PATH . DIRECTORY_SEPARATOR . 'Models' . DIRECTORY_SEPARATOR);
define('VIEW_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR);
define('ASSET_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'public/assets' . DIRECTORY_SEPARATOR);
define('LAYOUT_PATH', VIEW_PATH . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR);
define('HELPER_PATH', APP_PATH . DIRECTORY_SEPARATOR . 'Helpers' . DIRECTORY_SEPARATOR);
define('ROUTER_PATH', HELPER_PATH . DIRECTORY_SEPARATOR . 'Router.php');
define('UPLOAD_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR);
define('CACHE_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR);
define('CACHE_LIFETIME', 60 * 60 * 24); // 1 day in seconds